const express = require('express');
const expressLayouts = require('express-ejs-layouts');
const app = express();
const flash = require('connect-flash');
const session = require('express-session');
const passport = require('passport');

const index_routes = require('./routes/index');
const users_routes = require('./routes/users');
const dashboard_routes = require('./routes/dashboard');
const req = require('express/lib/request');

// Passport config
require('./config/passport')(passport);
//ejs 
app.use(expressLayouts);
app.set('view engine','ejs');

//body parser
app.use(express.urlencoded({ extended: false}));

// Express Session
app.use(session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: false
  }))

  // passport middleware
  app.use(passport.initialize());
  app.use(passport.session());

//connect flash
app.use(flash());

// Global Variable
app.use((req,res,next) => {
    res.locals.success_msg = req.flash('success_msg');
    res.locals.error_msg = req.flash('error_msg');
    res.locals.error_msg1 = req.flash('error_msg1');
    res.locals.error = req.flash('error'); // error generated by the passport.authenticate.
    next();
});

//routes
app.use('/', index_routes);
app.use('/users',users_routes);
app.use('/dashboard',dashboard_routes);
const PORT = process.env.PORT || 5000;

app.listen(PORT, console.log(`server started on port ${PORT} `));

